/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AdaptiveDifficulty
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class EventControlData : TBase
  {
    private Dictionary<string, EventConfig> _eventConfig;

    public Dictionary<string, EventConfig> EventConfig
    {
      get
      {
        return _eventConfig;
      }
      set
      {
        __isset.eventConfig = true;
        this._eventConfig = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool eventConfig;
    }

    public EventControlData() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.Map) {
              {
                EventConfig = new Dictionary<string, EventConfig>();
                TMap _map25 = iprot.ReadMapBegin();
                for( int _i26 = 0; _i26 < _map25.Count; ++_i26)
                {
                  string _key27;
                  EventConfig _val28;
                  _key27 = iprot.ReadString();
                  _val28 = new EventConfig();
                  _val28.Read(iprot);
                  EventConfig[_key27] = _val28;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("EventControlData");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (EventConfig != null && __isset.eventConfig) {
        field.Name = "eventConfig";
        field.Type = TType.Map;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.Struct, EventConfig.Count));
          foreach (string _iter29 in EventConfig.Keys)
          {
            oprot.WriteString(_iter29);
            EventConfig[_iter29].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("EventControlData(");
      sb.Append("EventConfig: ");
      sb.Append(EventConfig);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
