/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ActionEditor
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ActionFrameData : TBase
  {
    private double _time;
    private int _type;
    private SetCameraFrameConfig _setCameraFrame;
    private MoveCameraFrameConfig _moveCameraFrame;

    public double Time
    {
      get
      {
        return _time;
      }
      set
      {
        __isset.time = true;
        this._time = value;
      }
    }

    public int Type
    {
      get
      {
        return _type;
      }
      set
      {
        __isset.type = true;
        this._type = value;
      }
    }

    public SetCameraFrameConfig SetCameraFrame
    {
      get
      {
        return _setCameraFrame;
      }
      set
      {
        __isset.setCameraFrame = true;
        this._setCameraFrame = value;
      }
    }

    public MoveCameraFrameConfig MoveCameraFrame
    {
      get
      {
        return _moveCameraFrame;
      }
      set
      {
        __isset.moveCameraFrame = true;
        this._moveCameraFrame = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool time;
      public bool type;
      public bool setCameraFrame;
      public bool moveCameraFrame;
    }

    public ActionFrameData() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Double) {
              Time = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Type = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.Struct) {
              SetCameraFrame = new SetCameraFrameConfig();
              SetCameraFrame.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.Struct) {
              MoveCameraFrame = new MoveCameraFrameConfig();
              MoveCameraFrame.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ActionFrameData");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.time) {
        field.Name = "time";
        field.Type = TType.Double;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Time);
        oprot.WriteFieldEnd();
      }
      if (__isset.type) {
        field.Name = "type";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Type);
        oprot.WriteFieldEnd();
      }
      if (SetCameraFrame != null && __isset.setCameraFrame) {
        field.Name = "setCameraFrame";
        field.Type = TType.Struct;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        SetCameraFrame.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (MoveCameraFrame != null && __isset.moveCameraFrame) {
        field.Name = "moveCameraFrame";
        field.Type = TType.Struct;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        MoveCameraFrame.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ActionFrameData(");
      sb.Append("Time: ");
      sb.Append(Time);
      sb.Append(",Type: ");
      sb.Append(Type);
      sb.Append(",SetCameraFrame: ");
      sb.Append(SetCameraFrame== null ? "<null>" : SetCameraFrame.ToString());
      sb.Append(",MoveCameraFrame: ");
      sb.Append(MoveCameraFrame== null ? "<null>" : MoveCameraFrame.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
