/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ActionEditor
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class AddStateEffectFrameConfig : TBase
  {
    private string _effectName;
    private Common.Auto.ThriftVector3 _pos;
    private Common.Auto.ThriftVector3 _rot;
    private int _instanceId;
    private bool _isAttach;
    private EntityType _entityType;
    private int _attachNpcId;
    private string _attachPoingName;

    public string EffectName
    {
      get
      {
        return _effectName;
      }
      set
      {
        __isset.effectName = true;
        this._effectName = value;
      }
    }

    public Common.Auto.ThriftVector3 Pos
    {
      get
      {
        return _pos;
      }
      set
      {
        __isset.pos = true;
        this._pos = value;
      }
    }

    public Common.Auto.ThriftVector3 Rot
    {
      get
      {
        return _rot;
      }
      set
      {
        __isset.rot = true;
        this._rot = value;
      }
    }

    public int InstanceId
    {
      get
      {
        return _instanceId;
      }
      set
      {
        __isset.instanceId = true;
        this._instanceId = value;
      }
    }

    public bool IsAttach
    {
      get
      {
        return _isAttach;
      }
      set
      {
        __isset.isAttach = true;
        this._isAttach = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="EntityType"/>
    /// </summary>
    public EntityType EntityType
    {
      get
      {
        return _entityType;
      }
      set
      {
        __isset.entityType = true;
        this._entityType = value;
      }
    }

    public int AttachNpcId
    {
      get
      {
        return _attachNpcId;
      }
      set
      {
        __isset.attachNpcId = true;
        this._attachNpcId = value;
      }
    }

    public string AttachPoingName
    {
      get
      {
        return _attachPoingName;
      }
      set
      {
        __isset.attachPoingName = true;
        this._attachPoingName = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool effectName;
      public bool pos;
      public bool rot;
      public bool instanceId;
      public bool isAttach;
      public bool entityType;
      public bool attachNpcId;
      public bool attachPoingName;
    }

    public AddStateEffectFrameConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.String) {
              EffectName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.Struct) {
              Pos = new Common.Auto.ThriftVector3();
              Pos.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 30:
            if (field.Type == TType.Struct) {
              Rot = new Common.Auto.ThriftVector3();
              Rot.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 40:
            if (field.Type == TType.I32) {
              InstanceId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 50:
            if (field.Type == TType.Bool) {
              IsAttach = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 60:
            if (field.Type == TType.I32) {
              EntityType = (EntityType)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 70:
            if (field.Type == TType.I32) {
              AttachNpcId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 80:
            if (field.Type == TType.String) {
              AttachPoingName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("AddStateEffectFrameConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (EffectName != null && __isset.effectName) {
        field.Name = "effectName";
        field.Type = TType.String;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(EffectName);
        oprot.WriteFieldEnd();
      }
      if (Pos != null && __isset.pos) {
        field.Name = "pos";
        field.Type = TType.Struct;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        Pos.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Rot != null && __isset.rot) {
        field.Name = "rot";
        field.Type = TType.Struct;
        field.ID = 30;
        oprot.WriteFieldBegin(field);
        Rot.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.instanceId) {
        field.Name = "instanceId";
        field.Type = TType.I32;
        field.ID = 40;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(InstanceId);
        oprot.WriteFieldEnd();
      }
      if (__isset.isAttach) {
        field.Name = "isAttach";
        field.Type = TType.Bool;
        field.ID = 50;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(IsAttach);
        oprot.WriteFieldEnd();
      }
      if (__isset.entityType) {
        field.Name = "entityType";
        field.Type = TType.I32;
        field.ID = 60;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)EntityType);
        oprot.WriteFieldEnd();
      }
      if (__isset.attachNpcId) {
        field.Name = "attachNpcId";
        field.Type = TType.I32;
        field.ID = 70;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(AttachNpcId);
        oprot.WriteFieldEnd();
      }
      if (AttachPoingName != null && __isset.attachPoingName) {
        field.Name = "attachPoingName";
        field.Type = TType.String;
        field.ID = 80;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(AttachPoingName);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("AddStateEffectFrameConfig(");
      sb.Append("EffectName: ");
      sb.Append(EffectName);
      sb.Append(",Pos: ");
      sb.Append(Pos== null ? "<null>" : Pos.ToString());
      sb.Append(",Rot: ");
      sb.Append(Rot== null ? "<null>" : Rot.ToString());
      sb.Append(",InstanceId: ");
      sb.Append(InstanceId);
      sb.Append(",IsAttach: ");
      sb.Append(IsAttach);
      sb.Append(",EntityType: ");
      sb.Append(EntityType);
      sb.Append(",AttachNpcId: ");
      sb.Append(AttachNpcId);
      sb.Append(",AttachPoingName: ");
      sb.Append(AttachPoingName);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
