/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ActionEditor
{
  public enum EntityType
  {
    Camera = 0,
    Npc = 1,
    Player = 2,
  }
}
