/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CharactorConfigTable : TBase
  {
    private Dictionary<int, Config.CharactorConfig> _charactorCofigMap;

    public Dictionary<int, Config.CharactorConfig> CharactorCofigMap
    {
      get
      {
        return _charactorCofigMap;
      }
      set
      {
        __isset.charactorCofigMap = true;
        this._charactorCofigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool charactorCofigMap;
    }

    public CharactorConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                CharactorCofigMap = new Dictionary<int, Config.CharactorConfig>();
                TMap _map20 = iprot.ReadMapBegin();
                for( int _i21 = 0; _i21 < _map20.Count; ++_i21)
                {
                  int _key22;
                  Config.CharactorConfig _val23;
                  _key22 = iprot.ReadI32();
                  _val23 = new Config.CharactorConfig();
                  _val23.Read(iprot);
                  CharactorCofigMap[_key22] = _val23;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CharactorConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (CharactorCofigMap != null && __isset.charactorCofigMap) {
        field.Name = "charactorCofigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, CharactorCofigMap.Count));
          foreach (int _iter24 in CharactorCofigMap.Keys)
          {
            oprot.WriteI32(_iter24);
            CharactorCofigMap[_iter24].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CharactorConfigTable(");
      sb.Append("CharactorCofigMap: ");
      sb.Append(CharactorCofigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
