/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ItemConfigTable : TBase
  {
    private Dictionary<int, Config.ItemConfig> _itemConfigMap;

    public Dictionary<int, Config.ItemConfig> ItemConfigMap
    {
      get
      {
        return _itemConfigMap;
      }
      set
      {
        __isset.itemConfigMap = true;
        this._itemConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool itemConfigMap;
    }

    public ItemConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                ItemConfigMap = new Dictionary<int, Config.ItemConfig>();
                TMap _map90 = iprot.ReadMapBegin();
                for( int _i91 = 0; _i91 < _map90.Count; ++_i91)
                {
                  int _key92;
                  Config.ItemConfig _val93;
                  _key92 = iprot.ReadI32();
                  _val93 = new Config.ItemConfig();
                  _val93.Read(iprot);
                  ItemConfigMap[_key92] = _val93;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ItemConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ItemConfigMap != null && __isset.itemConfigMap) {
        field.Name = "itemConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, ItemConfigMap.Count));
          foreach (int _iter94 in ItemConfigMap.Keys)
          {
            oprot.WriteI32(_iter94);
            ItemConfigMap[_iter94].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ItemConfigTable(");
      sb.Append("ItemConfigMap: ");
      sb.Append(ItemConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
