/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MusicGameSettingTable : TBase
  {
    private Dictionary<int, Config.MusicGameNoteKeyConfig> _musicConfigMap;

    public Dictionary<int, Config.MusicGameNoteKeyConfig> MusicConfigMap
    {
      get
      {
        return _musicConfigMap;
      }
      set
      {
        __isset.musicConfigMap = true;
        this._musicConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool musicConfigMap;
    }

    public MusicGameSettingTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                MusicConfigMap = new Dictionary<int, Config.MusicGameNoteKeyConfig>();
                TMap _map123 = iprot.ReadMapBegin();
                for( int _i124 = 0; _i124 < _map123.Count; ++_i124)
                {
                  int _key125;
                  Config.MusicGameNoteKeyConfig _val126;
                  _key125 = iprot.ReadI32();
                  _val126 = new Config.MusicGameNoteKeyConfig();
                  _val126.Read(iprot);
                  MusicConfigMap[_key125] = _val126;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MusicGameSettingTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (MusicConfigMap != null && __isset.musicConfigMap) {
        field.Name = "musicConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, MusicConfigMap.Count));
          foreach (int _iter127 in MusicConfigMap.Keys)
          {
            oprot.WriteI32(_iter127);
            MusicConfigMap[_iter127].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("MusicGameSettingTable(");
      sb.Append("MusicConfigMap: ");
      sb.Append(MusicConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
