/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class StateConflictTable : TBase
  {
    private Dictionary<int, Config.StateConflictConfig> _stateConflictConfigMap;

    public Dictionary<int, Config.StateConflictConfig> StateConflictConfigMap
    {
      get
      {
        return _stateConflictConfigMap;
      }
      set
      {
        __isset.stateConflictConfigMap = true;
        this._stateConflictConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool stateConflictConfigMap;
    }

    public StateConflictTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                StateConflictConfigMap = new Dictionary<int, Config.StateConflictConfig>();
                TMap _map15 = iprot.ReadMapBegin();
                for( int _i16 = 0; _i16 < _map15.Count; ++_i16)
                {
                  int _key17;
                  Config.StateConflictConfig _val18;
                  _key17 = iprot.ReadI32();
                  _val18 = new Config.StateConflictConfig();
                  _val18.Read(iprot);
                  StateConflictConfigMap[_key17] = _val18;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("StateConflictTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (StateConflictConfigMap != null && __isset.stateConflictConfigMap) {
        field.Name = "stateConflictConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, StateConflictConfigMap.Count));
          foreach (int _iter19 in StateConflictConfigMap.Keys)
          {
            oprot.WriteI32(_iter19);
            StateConflictConfigMap[_iter19].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("StateConflictTable(");
      sb.Append("StateConflictConfigMap: ");
      sb.Append(StateConflictConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
