/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NetFramework.Auto
{
  public enum ChatContentType
  {
    none = 0,
    equip = 1,
    hero = 2,
    item = 3,
    team = 4,
    gang = 5,
  }
}
