/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CSSyncHeroGroupMsg : TBase
  {
    private List<long> _groupList1;
    private List<long> _groupList2;
    private List<long> _groupList3;

    public List<long> GroupList1
    {
      get
      {
        return _groupList1;
      }
      set
      {
        __isset.groupList1 = true;
        this._groupList1 = value;
      }
    }

    public List<long> GroupList2
    {
      get
      {
        return _groupList2;
      }
      set
      {
        __isset.groupList2 = true;
        this._groupList2 = value;
      }
    }

    public List<long> GroupList3
    {
      get
      {
        return _groupList3;
      }
      set
      {
        __isset.groupList3 = true;
        this._groupList3 = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool groupList1;
      public bool groupList2;
      public bool groupList3;
    }

    public CSSyncHeroGroupMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                GroupList1 = new List<long>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  long _elem2 = 0;
                  _elem2 = iprot.ReadI64();
                  GroupList1.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                GroupList2 = new List<long>();
                TList _list3 = iprot.ReadListBegin();
                for( int _i4 = 0; _i4 < _list3.Count; ++_i4)
                {
                  long _elem5 = 0;
                  _elem5 = iprot.ReadI64();
                  GroupList2.Add(_elem5);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                GroupList3 = new List<long>();
                TList _list6 = iprot.ReadListBegin();
                for( int _i7 = 0; _i7 < _list6.Count; ++_i7)
                {
                  long _elem8 = 0;
                  _elem8 = iprot.ReadI64();
                  GroupList3.Add(_elem8);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CSSyncHeroGroupMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (GroupList1 != null && __isset.groupList1) {
        field.Name = "groupList1";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, GroupList1.Count));
          foreach (long _iter9 in GroupList1)
          {
            oprot.WriteI64(_iter9);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (GroupList2 != null && __isset.groupList2) {
        field.Name = "groupList2";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, GroupList2.Count));
          foreach (long _iter10 in GroupList2)
          {
            oprot.WriteI64(_iter10);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (GroupList3 != null && __isset.groupList3) {
        field.Name = "groupList3";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, GroupList3.Count));
          foreach (long _iter11 in GroupList3)
          {
            oprot.WriteI64(_iter11);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CSSyncHeroGroupMsg(");
      sb.Append("GroupList1: ");
      sb.Append(GroupList1);
      sb.Append(",GroupList2: ");
      sb.Append(GroupList2);
      sb.Append(",GroupList3: ");
      sb.Append(GroupList3);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
