/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NetFramework.Auto
{
  public enum FingerGuessingType
  {
    Rock = 0,
    Scissors = 1,
    Paper = 2,
  }
}
