/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NetFramework.Auto
{
  public enum HeroEquipmentEnhanceType
  {
    One = 0,
    All = 1,
  }
}
