/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  /// <summary>
  /// 阶段信息
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MissionStepStructInfo : TBase
  {
    private MissionStateEnumType _stepState;
    private int _counter1;
    private int _counter2;
    private int _counter3;

    /// <summary>
    /// 阶段任务状态
    /// 
    /// <seealso cref="MissionStateEnumType"/>
    /// </summary>
    public MissionStateEnumType StepState
    {
      get
      {
        return _stepState;
      }
      set
      {
        __isset.stepState = true;
        this._stepState = value;
      }
    }

    /// <summary>
    /// 计数器数字
    /// </summary>
    public int Counter1
    {
      get
      {
        return _counter1;
      }
      set
      {
        __isset.counter1 = true;
        this._counter1 = value;
      }
    }

    /// <summary>
    /// 计数器数字
    /// </summary>
    public int Counter2
    {
      get
      {
        return _counter2;
      }
      set
      {
        __isset.counter2 = true;
        this._counter2 = value;
      }
    }

    /// <summary>
    /// 计数器数字
    /// </summary>
    public int Counter3
    {
      get
      {
        return _counter3;
      }
      set
      {
        __isset.counter3 = true;
        this._counter3 = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool stepState;
      public bool counter1;
      public bool counter2;
      public bool counter3;
    }

    public MissionStepStructInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.I32) {
              StepState = (MissionStateEnumType)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.I32) {
              Counter1 = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 30:
            if (field.Type == TType.I32) {
              Counter2 = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 40:
            if (field.Type == TType.I32) {
              Counter3 = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MissionStepStructInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.stepState) {
        field.Name = "stepState";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)StepState);
        oprot.WriteFieldEnd();
      }
      if (__isset.counter1) {
        field.Name = "counter1";
        field.Type = TType.I32;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Counter1);
        oprot.WriteFieldEnd();
      }
      if (__isset.counter2) {
        field.Name = "counter2";
        field.Type = TType.I32;
        field.ID = 30;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Counter2);
        oprot.WriteFieldEnd();
      }
      if (__isset.counter3) {
        field.Name = "counter3";
        field.Type = TType.I32;
        field.ID = 40;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Counter3);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("MissionStepStructInfo(");
      sb.Append("StepState: ");
      sb.Append(StepState);
      sb.Append(",Counter1: ");
      sb.Append(Counter1);
      sb.Append(",Counter2: ");
      sb.Append(Counter2);
      sb.Append(",Counter3: ");
      sb.Append(Counter3);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
