/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  /// <summary>
  /// 任务信息
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MissionStructInfo : TBase
  {
    private int _missionId;
    private MissionStateEnumType _missionStateEnumType;
    private sbyte _stepIndex;
    private MissionStepStructInfo _missionStepStructInfo;

    public int MissionId
    {
      get
      {
        return _missionId;
      }
      set
      {
        __isset.missionId = true;
        this._missionId = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="MissionStateEnumType"/>
    /// </summary>
    public MissionStateEnumType MissionStateEnumType
    {
      get
      {
        return _missionStateEnumType;
      }
      set
      {
        __isset.missionStateEnumType = true;
        this._missionStateEnumType = value;
      }
    }

    /// <summary>
    /// 步骤索引
    /// </summary>
    public sbyte StepIndex
    {
      get
      {
        return _stepIndex;
      }
      set
      {
        __isset.stepIndex = true;
        this._stepIndex = value;
      }
    }

    public MissionStepStructInfo MissionStepStructInfo
    {
      get
      {
        return _missionStepStructInfo;
      }
      set
      {
        __isset.missionStepStructInfo = true;
        this._missionStepStructInfo = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool missionId;
      public bool missionStateEnumType;
      public bool stepIndex;
      public bool missionStepStructInfo;
    }

    public MissionStructInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.I32) {
              MissionId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 11:
            if (field.Type == TType.I32) {
              MissionStateEnumType = (MissionStateEnumType)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.Byte) {
              StepIndex = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 30:
            if (field.Type == TType.Struct) {
              MissionStepStructInfo = new MissionStepStructInfo();
              MissionStepStructInfo.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MissionStructInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.missionId) {
        field.Name = "missionId";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(MissionId);
        oprot.WriteFieldEnd();
      }
      if (__isset.missionStateEnumType) {
        field.Name = "missionStateEnumType";
        field.Type = TType.I32;
        field.ID = 11;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)MissionStateEnumType);
        oprot.WriteFieldEnd();
      }
      if (__isset.stepIndex) {
        field.Name = "stepIndex";
        field.Type = TType.Byte;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(StepIndex);
        oprot.WriteFieldEnd();
      }
      if (MissionStepStructInfo != null && __isset.missionStepStructInfo) {
        field.Name = "missionStepStructInfo";
        field.Type = TType.Struct;
        field.ID = 30;
        oprot.WriteFieldBegin(field);
        MissionStepStructInfo.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("MissionStructInfo(");
      sb.Append("MissionId: ");
      sb.Append(MissionId);
      sb.Append(",MissionStateEnumType: ");
      sb.Append(MissionStateEnumType);
      sb.Append(",StepIndex: ");
      sb.Append(StepIndex);
      sb.Append(",MissionStepStructInfo: ");
      sb.Append(MissionStepStructInfo== null ? "<null>" : MissionStepStructInfo.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
