/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NetWork.Auto
{
  public enum MTMessageType
  {
    chatClosed = 1,
    saleClosed = 2,
    aotherCloseChat = 3,
    aotherCloseSale = 4,
    anotherAway = 5,
    chatTimeout = 6,
    saleTimeout = 7,
  }
}
