/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCAddHeroEquipmentMsg : TBase
  {
    private NetFramework.Auto.HeroEquipmentInfo _heroEquipmentInfo;

    public NetFramework.Auto.HeroEquipmentInfo HeroEquipmentInfo
    {
      get
      {
        return _heroEquipmentInfo;
      }
      set
      {
        __isset.heroEquipmentInfo = true;
        this._heroEquipmentInfo = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool heroEquipmentInfo;
    }

    public SCAddHeroEquipmentMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.Struct) {
              HeroEquipmentInfo = new NetFramework.Auto.HeroEquipmentInfo();
              HeroEquipmentInfo.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCAddHeroEquipmentMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (HeroEquipmentInfo != null && __isset.heroEquipmentInfo) {
        field.Name = "heroEquipmentInfo";
        field.Type = TType.Struct;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        HeroEquipmentInfo.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCAddHeroEquipmentMsg(");
      sb.Append("HeroEquipmentInfo: ");
      sb.Append(HeroEquipmentInfo== null ? "<null>" : HeroEquipmentInfo.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
