/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCArmyInfoMsg : TBase
  {
    private NetFramework.Auto.ArmyInfo _armyInfo;

    public NetFramework.Auto.ArmyInfo ArmyInfo
    {
      get
      {
        return _armyInfo;
      }
      set
      {
        __isset.armyInfo = true;
        this._armyInfo = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool armyInfo;
    }

    public SCArmyInfoMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.Struct) {
              ArmyInfo = new NetFramework.Auto.ArmyInfo();
              ArmyInfo.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCArmyInfoMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ArmyInfo != null && __isset.armyInfo) {
        field.Name = "armyInfo";
        field.Type = TType.Struct;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        ArmyInfo.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCArmyInfoMsg(");
      sb.Append("ArmyInfo: ");
      sb.Append(ArmyInfo== null ? "<null>" : ArmyInfo.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
