/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCBattleReusltMsg : TBase
  {
    private NetFramework.Auto.BattleResultType _battleResultType;
    private int _awardGold;
    private sbyte _star;

    /// <summary>
    /// 
    /// <seealso cref="NetFramework.Auto.BattleResultType"/>
    /// </summary>
    public NetFramework.Auto.BattleResultType BattleResultType
    {
      get
      {
        return _battleResultType;
      }
      set
      {
        __isset.battleResultType = true;
        this._battleResultType = value;
      }
    }

    public int AwardGold
    {
      get
      {
        return _awardGold;
      }
      set
      {
        __isset.awardGold = true;
        this._awardGold = value;
      }
    }

    public sbyte Star
    {
      get
      {
        return _star;
      }
      set
      {
        __isset.star = true;
        this._star = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool battleResultType;
      public bool awardGold;
      public bool star;
    }

    public SCBattleReusltMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.I32) {
              BattleResultType = (NetFramework.Auto.BattleResultType)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.I32) {
              AwardGold = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 30:
            if (field.Type == TType.Byte) {
              Star = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCBattleReusltMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.battleResultType) {
        field.Name = "battleResultType";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)BattleResultType);
        oprot.WriteFieldEnd();
      }
      if (__isset.awardGold) {
        field.Name = "awardGold";
        field.Type = TType.I32;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(AwardGold);
        oprot.WriteFieldEnd();
      }
      if (__isset.star) {
        field.Name = "star";
        field.Type = TType.Byte;
        field.ID = 30;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(Star);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCBattleReusltMsg(");
      sb.Append("BattleResultType: ");
      sb.Append(BattleResultType);
      sb.Append(",AwardGold: ");
      sb.Append(AwardGold);
      sb.Append(",Star: ");
      sb.Append(Star);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
