/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCDeleteTriggerMsg : TBase
  {
    private List<long> _triggerUniqueIdList;

    public List<long> TriggerUniqueIdList
    {
      get
      {
        return _triggerUniqueIdList;
      }
      set
      {
        __isset.triggerUniqueIdList = true;
        this._triggerUniqueIdList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool triggerUniqueIdList;
    }

    public SCDeleteTriggerMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.List) {
              {
                TriggerUniqueIdList = new List<long>();
                TList _list68 = iprot.ReadListBegin();
                for( int _i69 = 0; _i69 < _list68.Count; ++_i69)
                {
                  long _elem70 = 0;
                  _elem70 = iprot.ReadI64();
                  TriggerUniqueIdList.Add(_elem70);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCDeleteTriggerMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (TriggerUniqueIdList != null && __isset.triggerUniqueIdList) {
        field.Name = "triggerUniqueIdList";
        field.Type = TType.List;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, TriggerUniqueIdList.Count));
          foreach (long _iter71 in TriggerUniqueIdList)
          {
            oprot.WriteI64(_iter71);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCDeleteTriggerMsg(");
      sb.Append("TriggerUniqueIdList: ");
      sb.Append(TriggerUniqueIdList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
