/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCLeaveTriggerMsg : TBase
  {
    private long _triggerUniqueId;
    private List<long> _affectUniqueIdList;

    public long TriggerUniqueId
    {
      get
      {
        return _triggerUniqueId;
      }
      set
      {
        __isset.triggerUniqueId = true;
        this._triggerUniqueId = value;
      }
    }

    public List<long> AffectUniqueIdList
    {
      get
      {
        return _affectUniqueIdList;
      }
      set
      {
        __isset.affectUniqueIdList = true;
        this._affectUniqueIdList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool triggerUniqueId;
      public bool affectUniqueIdList;
    }

    public SCLeaveTriggerMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.I64) {
              TriggerUniqueId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.List) {
              {
                AffectUniqueIdList = new List<long>();
                TList _list60 = iprot.ReadListBegin();
                for( int _i61 = 0; _i61 < _list60.Count; ++_i61)
                {
                  long _elem62 = 0;
                  _elem62 = iprot.ReadI64();
                  AffectUniqueIdList.Add(_elem62);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCLeaveTriggerMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.triggerUniqueId) {
        field.Name = "triggerUniqueId";
        field.Type = TType.I64;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(TriggerUniqueId);
        oprot.WriteFieldEnd();
      }
      if (AffectUniqueIdList != null && __isset.affectUniqueIdList) {
        field.Name = "affectUniqueIdList";
        field.Type = TType.List;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, AffectUniqueIdList.Count));
          foreach (long _iter63 in AffectUniqueIdList)
          {
            oprot.WriteI64(_iter63);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCLeaveTriggerMsg(");
      sb.Append("TriggerUniqueId: ");
      sb.Append(TriggerUniqueId);
      sb.Append(",AffectUniqueIdList: ");
      sb.Append(AffectUniqueIdList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
