/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  /// <summary>
  /// 通知玩家处理申请结果
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCNoticeHandleApplyJoinMsg : TBase
  {
    private NetFramework.Auto.HandleApplyJoinType _handleType;
    private string _armyName;
    private NetFramework.Auto.ArmyInfo _armyInfo;

    /// <summary>
    /// 
    /// <seealso cref="NetFramework.Auto.HandleApplyJoinType"/>
    /// </summary>
    public NetFramework.Auto.HandleApplyJoinType HandleType
    {
      get
      {
        return _handleType;
      }
      set
      {
        __isset.handleType = true;
        this._handleType = value;
      }
    }

    public string ArmyName
    {
      get
      {
        return _armyName;
      }
      set
      {
        __isset.armyName = true;
        this._armyName = value;
      }
    }

    public NetFramework.Auto.ArmyInfo ArmyInfo
    {
      get
      {
        return _armyInfo;
      }
      set
      {
        __isset.armyInfo = true;
        this._armyInfo = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool handleType;
      public bool armyName;
      public bool armyInfo;
    }

    public SCNoticeHandleApplyJoinMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.I32) {
              HandleType = (NetFramework.Auto.HandleApplyJoinType)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.String) {
              ArmyName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 30:
            if (field.Type == TType.Struct) {
              ArmyInfo = new NetFramework.Auto.ArmyInfo();
              ArmyInfo.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCNoticeHandleApplyJoinMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.handleType) {
        field.Name = "handleType";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)HandleType);
        oprot.WriteFieldEnd();
      }
      if (ArmyName != null && __isset.armyName) {
        field.Name = "armyName";
        field.Type = TType.String;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ArmyName);
        oprot.WriteFieldEnd();
      }
      if (ArmyInfo != null && __isset.armyInfo) {
        field.Name = "armyInfo";
        field.Type = TType.Struct;
        field.ID = 30;
        oprot.WriteFieldBegin(field);
        ArmyInfo.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCNoticeHandleApplyJoinMsg(");
      sb.Append("HandleType: ");
      sb.Append(HandleType);
      sb.Append(",ArmyName: ");
      sb.Append(ArmyName);
      sb.Append(",ArmyInfo: ");
      sb.Append(ArmyInfo== null ? "<null>" : ArmyInfo.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
