/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCRefleshRecommendMsg : TBase
  {
    private List<NetFramework.Auto.FriendInfo> _recommendList;

    public List<NetFramework.Auto.FriendInfo> RecommendList
    {
      get
      {
        return _recommendList;
      }
      set
      {
        __isset.recommendList = true;
        this._recommendList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool recommendList;
    }

    public SCRefleshRecommendMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                RecommendList = new List<NetFramework.Auto.FriendInfo>();
                TList _list4 = iprot.ReadListBegin();
                for( int _i5 = 0; _i5 < _list4.Count; ++_i5)
                {
                  NetFramework.Auto.FriendInfo _elem6 = new NetFramework.Auto.FriendInfo();
                  _elem6 = new NetFramework.Auto.FriendInfo();
                  _elem6.Read(iprot);
                  RecommendList.Add(_elem6);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCRefleshRecommendMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (RecommendList != null && __isset.recommendList) {
        field.Name = "recommendList";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, RecommendList.Count));
          foreach (NetFramework.Auto.FriendInfo _iter7 in RecommendList)
          {
            _iter7.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCRefleshRecommendMsg(");
      sb.Append("RecommendList: ");
      sb.Append(RecommendList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
