/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCSceneCharInfoSync : TBase
  {
    private List<NetFramework.Auto.PostionInfoSync> _syncInfos;

    public List<NetFramework.Auto.PostionInfoSync> SyncInfos
    {
      get
      {
        return _syncInfos;
      }
      set
      {
        __isset.syncInfos = true;
        this._syncInfos = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool syncInfos;
    }

    public SCSceneCharInfoSync() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.List) {
              {
                SyncInfos = new List<NetFramework.Auto.PostionInfoSync>();
                TList _list4 = iprot.ReadListBegin();
                for( int _i5 = 0; _i5 < _list4.Count; ++_i5)
                {
                  NetFramework.Auto.PostionInfoSync _elem6 = new NetFramework.Auto.PostionInfoSync();
                  _elem6 = new NetFramework.Auto.PostionInfoSync();
                  _elem6.Read(iprot);
                  SyncInfos.Add(_elem6);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCSceneCharInfoSync");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (SyncInfos != null && __isset.syncInfos) {
        field.Name = "syncInfos";
        field.Type = TType.List;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, SyncInfos.Count));
          foreach (NetFramework.Auto.PostionInfoSync _iter7 in SyncInfos)
          {
            _iter7.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCSceneCharInfoSync(");
      sb.Append("SyncInfos: ");
      sb.Append(SyncInfos);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
