/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetFramework.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCSearchArmyMsg : TBase
  {
    private NetFramework.Auto.SimpleArmyInfo _simpleArmyInfo;

    public NetFramework.Auto.SimpleArmyInfo SimpleArmyInfo
    {
      get
      {
        return _simpleArmyInfo;
      }
      set
      {
        __isset.simpleArmyInfo = true;
        this._simpleArmyInfo = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool simpleArmyInfo;
    }

    public SCSearchArmyMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.Struct) {
              SimpleArmyInfo = new NetFramework.Auto.SimpleArmyInfo();
              SimpleArmyInfo.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCSearchArmyMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (SimpleArmyInfo != null && __isset.simpleArmyInfo) {
        field.Name = "simpleArmyInfo";
        field.Type = TType.Struct;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        SimpleArmyInfo.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCSearchArmyMsg(");
      sb.Append("SimpleArmyInfo: ");
      sb.Append(SimpleArmyInfo== null ? "<null>" : SimpleArmyInfo.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
