/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Config
{
  public enum DownloadAssetType
  {
    ConfigByte = 0,
    ConfigText = 1,
    Image = 2,
    Audio = 3,
    AssetBundle = 4,
  }
}
