/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class StateConflictConfig : TBase
  {
    private Dictionary<int, List<StateConflictConfigElement>> _stateConflictMap;

    public Dictionary<int, List<StateConflictConfigElement>> StateConflictMap
    {
      get
      {
        return _stateConflictMap;
      }
      set
      {
        __isset.stateConflictMap = true;
        this._stateConflictMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool stateConflictMap;
    }

    public StateConflictConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.Map) {
              {
                StateConflictMap = new Dictionary<int, List<StateConflictConfigElement>>();
                TMap _map36 = iprot.ReadMapBegin();
                for( int _i37 = 0; _i37 < _map36.Count; ++_i37)
                {
                  int _key38;
                  List<StateConflictConfigElement> _val39;
                  _key38 = iprot.ReadI32();
                  {
                    _val39 = new List<StateConflictConfigElement>();
                    TList _list40 = iprot.ReadListBegin();
                    for( int _i41 = 0; _i41 < _list40.Count; ++_i41)
                    {
                      StateConflictConfigElement _elem42 = new StateConflictConfigElement();
                      _elem42 = new StateConflictConfigElement();
                      _elem42.Read(iprot);
                      _val39.Add(_elem42);
                    }
                    iprot.ReadListEnd();
                  }
                  StateConflictMap[_key38] = _val39;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("StateConflictConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (StateConflictMap != null && __isset.stateConflictMap) {
        field.Name = "stateConflictMap";
        field.Type = TType.Map;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.List, StateConflictMap.Count));
          foreach (int _iter43 in StateConflictMap.Keys)
          {
            oprot.WriteI32(_iter43);
            {
              oprot.WriteListBegin(new TList(TType.Struct, StateConflictMap[_iter43].Count));
              foreach (StateConflictConfigElement _iter44 in StateConflictMap[_iter43])
              {
                _iter44.Write(oprot);
              }
              oprot.WriteListEnd();
            }
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("StateConflictConfig(");
      sb.Append("StateConflictMap: ");
      sb.Append(StateConflictMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
